# -----------------------------
# COMPETITORS
# -----------------------------

competitors = [

    "Interarch",
"Kirby Building Systems",
"Tata BlueScope Steel",
"Zamil Steel Buildings India",
"Everest Industries",
"PEBS Pennar",
"Pennar Industries",
"EPACK Prefab",
"Jindal Buildsys",
"Larsen & Toubro Construction",
"M&B Engineering",
"Tiger Steel Engineering",
"Multicolor Steels",
"Lloyd Insulations India",
"Astron Buildings",
"Sai Sudhir Infrastructures",
"SML Group",
"Mekins Industries",
"Phenix Construction Technologies",
"Shebond Infrastructure",
"JSW One Platforms",
"Kaizen Smartbuild",
"KMS Technologies",
"Vipul Infra Systems",
"Mechfab Engineering Industries",
"Moonwalk Infraprojects",
"Vedanshi Industries",
"Delta Infrastructures",
"Pennar Engineered Building Systems",
"Civil Engineering Enterprises",
"Indue Prefab",
"Aster PEB",
"Nova Buildings",
"SRMB Srijan",
"PEB Steel Lloyd",
"Future Tech Infra",
"Shiv Shakti Fabricators",
"Steel Build Infra Projects",
"Riddhi Siddhi PEB",
"Western Steel Buildings",
"Precision Precast Solutions",
"Noble PEB Fabricators",
"Steelon Buildsys",
"PEB Structures India",
"Multi Decor India",
"Apex Buildsys",
"Metal Mart",
"PEB Surya Infra",
"North India Steel Buildings",
"Aarna Buildtech",
"PEB Buildtech Solutions",
"Modern Industrial Structures",
"Jindal Prefab",
"Minda Infrastructure",
"Uno Minda Infrastructure",
"ECR Buildtech",
"Group Surya",
"REDi Infraworks",
"DC FAB Engineering Contractors",
"Steelbuild Infra Projects",
"Phenixx Smartbuild",
"Corrit Energy & Infra",
"Gind Infra",
"HG Infra Engineering",
"Midas India",
"Kaizen Smartbuild",
"Tiger Steel Engineering",
"Vipul Infra Projects",
"Steelon Buildsys",
"PEB Surya Infra",
"Future Tech Infra",
"Delta Infrastructures",
"Shiv Shakti Fabricators",
"Western Steel Buildings",
"Riddhi Siddhi PEB",
"North India Steel Buildings",
"PEB Buildtech Solutions",
"Aarna Buildtech",
"Nova Buildings",
"Aster PEB",
"Mechfab Engineering Industries",
"Moonwalk Infraprojects",
"Civil Engineering Enterprises",
"Indue Prefab",
"Shebond Infrastructure",
"Phenix Construction Technologies",
"Sai Sudhir Infrastructures",
"M&B Engineering",
"Interarch Building Products",
"Kirby Building Systems",
"Tata BlueScope Steel",
"Zamil Steel Buildings India",
"Everest Industries",
"EPACK Prefab",
"PEBS Pennar",
"Pennar Industries",
"Jindal Buildsys",
"JSW One Platforms",
"Larsen & Toubro Construction",
"Multicolor Steels",
"SML Group",
"Mekins Industries",
"Lloyd Insulations India",
"Astron Buildings"

]

# -----------------------------
# POTENTIAL CLIENTS
# -----------------------------

clients = [

"Reliance Industries",
"Reliance Retail",
"Reliance Jio",
"Adani Group",
"Adani Enterprises",
"Adani Ports",
"Adani Green Energy",
"Tata Group",
"Tata Steel",
"Tata Projects",
"Tata Power",
"Tata Advanced Systems",
"Polycab India",
"JSW Group",
"JSW Steel",
"Jindal Steel & Power",
"Jindal Stainless",
"Vedanta Group",
"Hindalco Industries",
"Birla Group",
"UltraTech Cement",
"Grasim Industries",
"Larsen & Toubro",
"L&T Construction",
"Godrej & Boyce",
"Godrej Properties",
"Mahindra Group",
"Mahindra Susten",
"Mahindra Logistics",
"Ashok Leyland",
"TVS Group",
"CEAT",
"Bajaj Auto",
"Hero MotoCorp",
"Maruti Suzuki",
"Toyota Kirloskar",
"Honda Cars India",
"Hyundai Motor India",
"Kia India",
"MG Motor India",
"Tata Motors",
"Force Motors",
"Eicher Motors",
"Ather Energy",
"Ola Electric",
"Amara Raja",
"Exide Industries",
"Havells India",
"KEI Industries",
"Finolex Cables",
"RR Kabel",
"Anchor Electricals",
"Schneider Electric India",
"Siemens India",
"ABB India",
"Crompton Greaves",
"Kirloskar Brothers",
"Cummins India",
"Thermax",
"Bharat Forge",
"SKF India",
"Bosch India",
"Saint-Gobain India",
"Asian Paints",
"Berger Paints",
"Kansai Nerolac",
"Pidilite Industries",
"Shree Cement",
"ACC Cement",
"Ambuja Cement",
"Dalmia Bharat",
"JK Cement",
"Ramco Cements",
"ITC Limited",
"HUL",
"Nestle India",
"Britannia Industries",
"PepsiCo India",
"Coca-Cola India",
"Parle Agro",
"Dabur India",
"Emami",
"Marico",
"Aditya Birla Fashion",
"Arvind Limited",
"Raymond",
"Welspun India",
"Vardhman Textiles",
"Page Industries",
"Infosys",
"TCS",
"Wipro",
"HCL Technologies",
"Tech Mahindra",
"Cognizant India",
"Capgemini India",
"Accenture India",
"Amazon India",
"Flipkart",
"Walmart India",
"DMart",
"BigBasket",
"Zepto",
"Blinkit",
"Swiggy",
"Zomato",
"Delhivery",
"Blue Dart",
"Safexpress",
"Allcargo Logistics",
"Gati",
"Container Corporation of India",
"NHPC",
"NTPC",
"Power Grid Corporation",
"Indian Oil Corporation",
"Bharat Petroleum",
"Hindustan Petroleum",
"ONGC",
"GAIL India",
"Coal India",
"SAIL",
"BHEL",
"DRDO",
"ISRO",
"Airport Authority of India",
"Indian Railways",
"Dedicated Freight Corridor Corporation",
"NHAI",
"Reliance Industries",
"Adani Group",
"Tata Electronics",
"Tata Advanced Systems",
"Tata Power Solar",
"JSW Steel",
"JSW Energy",
"AMNS India",
"Vedanta",
"Hindalco Industries",
"UltraTech Cement",
"Aditya Birla Group",
"Grasim Industries",
"Dalmia Bharat",
"Shree Cement",
"Ambuja Cement",
"ACC Cement",
"JK Cement",
"Ramco Cements",
"Greenpanel Industries",
"Action TESA",
"Century Plyboards",
"Astral Pipes",
"Supreme Industries",
"Finolex Industries",
"Prince Pipes",
"Polycab India",
"KEI Industries",
"RR Kabel",
"Havells India",
"Dixon Technologies",
"Amber Enterprises",
"PG Electroplast",
"Kaynes Technology",
"Syrma SGS",
"Tata Motors",
"Mahindra & Mahindra",
"Maruti Suzuki",
"Hyundai India",
"Kia India",
"Ola Electric",
"Ather Energy",
"TVS Motor",
"Hero MotoCorp",
"Bajaj Auto",
"Ashok Leyland",
"Eicher Motors",
"Exide Industries",
"Amara Raja Energy",
"Uno Minda",
"Motherson",
"Sona Comstar",
"Bharat Forge",
"JBM Auto",
"Varroc Engineering",
"CEAT",
"MRF",
"Apollo Tyres",
"Balkrishna Industries",
"Pidilite Industries",
"Asian Paints",
"Berger Paints",
"Kansai Nerolac",
"Pidilite",
"ITC",
"Britannia Industries",
"Nestle India",
"Dabur India",
"Marico",
"Emami",
"Parle Agro",
"PepsiCo India",
"Coca-Cola India",
"Haldiram Foods",
"Amul",
"Mother Dairy",
"Hatsun Agro",
"Reliance Retail",
"Flipkart",
"Amazon India",
"DMart",
"BigBasket",
"Blinkit",
"Zepto",
"Swiggy Instamart",
"Delhivery",
"Blue Dart",
"Safexpress",
"Allcargo Logistics",
"Xpressbees",
"Ecom Express",
"Shadowfax",
"Adani Logistics",
"Container Corporation of India",
"Coldman Logistics",
"Snowman Logistics",
"Infosys",
"TCS",
"Wipro",
"HCL Technologies",
"Tech Mahindra",
"Foxconn India",
"Micron India",
"Intel India",
"Samsung India",
"Apple Suppliers India",
"Lenskart",
"Nykaa",
"Wakefit",
"Pepperfry",
"Urban Ladder",
"Godrej Appliances",
"Voltas",
"Blue Star",
"Daikin India",
"Carrier India",
"Schneider Electric India",
"ABB India",
"Siemens India",
"Cummins India",
"Kirloskar Brothers",
"Thermax",
"Waaree Energies",
"Adani Solar",
"Premier Energies",
"Vikram Solar",
"Renew Power",
"NTPC Green Energy",
"Torrent Power",
"Suzlon Energy",
"Inox Wind",
"Azure Power",
"Greenko",
"ReNew",
"Gensol Engineering"

]

# -----------------------------
# STEEL & PROCUREMENT
# -----------------------------

steel_keywords = [

    "steel price",
    "HRC",
    "CRC",
    "iron ore",
    "scrap price",
    "metal market",
    "zinc price",
    "steel demand",
     "Steel Price",
"Steel Prices",
"Steel Rate",
"Steel Market Price",
"Steel Cost Increase",
"Steel Price Hike",
"Steel Price Drop",
"Structural Steel Price",
"MS Steel Price",
"TMT Price",
"HR Coil Price",
"HRC Price",
"Hot Rolled Coil",
"Cold Rolled Coil",
"CRC Price",
"Galvanized Steel Price",
"GI Coil Price",
"Color Coated Coil",
"PPGI Coil",
"Zinc Price",
"Iron Ore Price",
"Coking Coal Price",
"Scrap Steel Price",
"Steel Raw Material Cost",
"Steel Procurement",
"Steel Demand",
"Domestic Steel Demand",
"Industrial Steel Demand",
"Construction Steel Demand",
"Steel Consumption",
"Steel Industry Outlook",
"Steel Market Outlook",
"Steel Capacity Expansion",
"Steel Production",
"Steel Output",
"Steel Export",
"Steel Import",
"Steel Industry News",
"Steel Sector Growth",
"Steel Sector Investment",
"Steel Plant Expansion",
"Steel Manufacturing Capacity",
"Structural Steel",
"PEB Raw Material",
"PEB Steel",
"Steel Section",
"Built Up Section",
"I Beam",
"H Beam",
"C Channel",
"Z Purlin",
"Steel Coil",
"MS Plate",
"MS Pipe",
"Roofing Sheet",
"Color Coated Sheet",
"Sandwich Panel",
"Insulated Panel",
"PUF Panel",
"Rockwool Panel",
"Industrial Roofing Sheet",
"Deck Sheet",
"Pre Painted Steel",
"Galvalume Sheet",
"PEB Roofing Material",
"Industrial Cladding",
"Warehouse Roofing",
"PEB Component",
"Steel Fabrication Material",
"Industrial Shed Material",
"Infrastructure Spending",
"Government Capex",
"Public Infrastructure Investment",
"Construction Demand",
"Industrial Construction Growth",
"Manufacturing Expansion",
"Warehouse Demand",
"Logistics Demand",
"Industrial Real Estate Demand",
"Commercial Construction",
"Factory Expansion",
"Industrial Park Development",
"Mega Project",
"Industrial Investment",
"Capex Cycle",
"Private Capex",
"Construction Sector Growth",
"Industrial Growth",
"Infrastructure Pipeline",
"Construction Material Demand",
"Building Material Price",
"Cement Price",
"Industrial Roofing Demand",
"Warehouse Construction Boom",
"Warehouse Leasing",
"Warehouse Demand",
"Grade A Warehouse",
"Logistics Park Development",
"Ecommerce Warehouse Expansion",
"3PL Expansion",
"Supply Chain Expansion",
"Distribution Center",
"Cold Storage Demand",
"Industrial Warehouse",
"Built To Suit Warehouse",
"Mega Warehouse Project",
"Warehouse Construction",
"Industrial Leasing",
"Logistics Infrastructure Growth",
"New Manufacturing Plant",
"Factory Expansion",
"Greenfield Project",
"Brownfield Expansion",
"Capacity Expansion",
"Production Capacity",
"Plant Commissioning",
"Industrial Capex",
"Manufacturing Investment",
"New Industrial Unit",
"Upcoming Factory",
"Industrial Expansion Plan",
"Mega Manufacturing Project",
"Plant Construction",
"Factory Setup",
"Production Facility Expansion",
"JSW Steel",
"Tata Steel",
"SAIL",
"Jindal Steel",
"AMNS India",
"Bhushan Steel",
"APL Apollo",
"Pennar Industries",
"Interarch",
"Kirby Building Systems",
"Tata BlueScope",
"PEBS Pennar",
"Zamil Steel",
"Everest Industries",
"EPACK Prefab",
"M&B Engineering",
"Jindal Buildsys",
"JSW One",
"APL Apollo Tubes",
"steel price increase india",
"structural steel demand india",
"warehouse construction india",
"industrial capex india",
"manufacturing expansion india",
"new factory announcement india",
"logistics park project india",
"steel industry outlook india",
"government infrastructure spending india",
"industrial park development india",
"PEB industry growth india",
"pre engineered building market india",
"industrial construction growth india",
"steel consumption india",
"hot rolled coil price india",
"galvanized steel price india",
"roofing sheet price india",
"warehouse leasing india",
"data center expansion india",
"solar manufacturing plant india"

]

# -----------------------------
# DEMAND DRIVERS
# -----------------------------

demand_keywords = [

    "PEB",
"Pre Engineered Building",
"Pre Engineered Buildings",
"Pre Engineered Steel Building",
"PEB Structure",
"PEB Shed",
"PEB Warehouse",
"PEB Factory",
"PEB Industrial Shed",
"PEB Contractor",
"PEB Manufacturer",
"PEB Company",
"PEB Building Contractor",
"PEB Construction",
"PEB Roofing",
"PEB Steel Structure",
"PEB Solutions",
"PEB Infrastructure",
"Steel Building",
"Steel Structure",
"Structural Steel",
"Steel Fabrication",
"Steel Fabricator",
"Industrial Steel Structure",
"Heavy Steel Structure",
"Structural Engineering",
"Steel Infrastructure",
"Industrial Shed",
"Factory Shed",
"Industrial Building",
"Industrial Construction",
"Industrial Infrastructure",
"Industrial Project",
"Industrial Contractor",
"Industrial EPC",
"Turnkey Industrial Project",
"Turnkey Industrial Building",
"Factory Construction",
"Warehouse Construction",
"Warehouse Shed",
"Warehouse Building",
"Warehouse Infrastructure",
"Logistics Warehouse",
"Fulfillment Center",
"Distribution Center",
"Cold Storage",
"Industrial Warehouse",
"Logistics Park",
"Mega Warehouse",
"Grade A Warehouse",
"Storage Facility",
"Supply Chain Infrastructure",
"Prefab Building",
"Prefabricated Building",
"Pre Fabricated Building",
"Pre Fabricated Structure",
"Prefab Structure",
"Prefabricated Structure",
"Modular Building",
"Modular Construction",
"Portable Building",
"Portable Cabin",
"Portable Office",
"Site Office Cabin",
"Container Office",
"Modular Office",
"Temporary Structure",
"Industrial Roofing",
"Roofing Structure",
"Metal Building",
"Metal Structure",
"Metal Shed",
"Sheeting Contractor",
"Roofing Contractor",
"Portal Frame",
"Built Up Section",
"Hot Rolled Section",
"Cold Formed Structure",
"Mezzanine Structure",
"Pipe Rack Structure",
"Canopy Structure",
"Space Frame",
"Design Build",
"Design Build Contractor",
"EPC Contractor",
"Engineering Procurement Construction",
"Industrial Civil Contractor",
"Infrastructure EPC",
"Turnkey Contractor",
"Industrial Developer",
"Industrial Park",
"Industrial Estate",
"Industrial Cluster",
"Industrial Township",
"Smart Industrial Park",
"Built To Suit",
"BTS Facility",
"Plug And Play Factory",
"SEZ",
"GIDC",
"MIDC",
"Manufacturing Plant",
"Manufacturing Facility",
"Production Facility",
"Factory Expansion",
"Industrial Expansion",
"Plant Expansion",
"Greenfield Project",
"Brownfield Expansion",
"Capex Announcement",
"Capacity Addition",
"New Manufacturing Unit",
"New Industrial Unit",
"Upcoming Plant",
"Industrial Investment",
"Manufacturing Investment",
"Factory Setup",
"Construction Begins",
"Project Awarded",
"Groundbreaking Ceremony",
"Commissioning",
"MoU Signed",
"Warehouse Expansion",
"Logistics Expansion",
"Ecommerce Warehouse",
"3PL Warehouse",
"Freight Corridor",
"Supply Chain Facility",
"Cold Chain Infrastructure",
"Data Center",
"Hyperscale Data Center",
"Server Facility",
"Cloud Infrastructure",
"AI Data Center",
"Semiconductor Plant",
"Electronics Manufacturing",
"EMS Facility",
"Electronics Park",
"Chip Manufacturing",
"Solar Manufacturing Plant",
"Solar Module Plant",
"Battery Plant",
"Gigafactory",
"EV Plant",
"Renewable Energy Park",
"Green Hydrogen Plant",
"Wind Turbine Plant",
"Energy Storage Facility",
"Renewable Infrastructure",
"Industrial Real Estate",
"Commercial Warehouse",
"Infrastructure Development",
"Industrial Capex",
"Mega Project",
"Large Scale Infrastructure",
"Industrial Engineering",
"Construction Technology",
"Smart Factory",
"Automated Warehouse",
"Integrated Manufacturing Facility",
"Logistics Infrastructure",
"Factory Infrastructure",
"Industrial Automation Facility",
"Advanced Manufacturing Facility",
"warehouse expansion india",
"new manufacturing plant india",
"logistics park investment",
"factory expansion",
"industrial shed project",
"new industrial unit",
"data center india",
"solar manufacturing plant",
"gigafactory india",
"industrial park project",
"greenfield project india",
"brownfield expansion",
"steel structure project",
"prefab building india",
"PEB warehouse project",
"EPC industrial project",
"expansion",
"capacity addition",
"new plant",
"new factory",
"capex",
"greenfield",
"brownfield",
"commissioning",
"groundbreaking",
"MoU signed",
"industrial park",
"warehouse leasing",
"manufacturing facility",
"construction begins",
"project awarded",
"capacity addition",
"greenfield",
"brownfield",
"expansion",
"commissioning",
"project awarded",
"construction begins",
"land acquisition",
"MoU signed",
"investment announced",
"plant setup",
"factory setup",
"industrial park",
"warehouse leasing",
"new facility",
"manufacturing hub",
"industrial cluster",
"infra boost",
"government capex",
"tender floated",
"Pre Engineered Building Export",
"PEB Export",
"Steel Structure Export",
"Prefab Building Export",
"Modular Building Export",
"Prefabricated Structure Export",
"Steel Building Export",
"Industrial Shed Export",
"Warehouse Structure Export",
"Turnkey Steel Building Export",
"Pre Engineered Steel Building Supply",
"International EPC Project",
"Overseas EPC Contract",
"Global Construction Project",
"International Industrial Project",
"Turnkey Warehouse Project",
"Industrial Construction Export",
"Export of Steel Fabrication",
"Structural Steel Export",
"Fabricated Steel Structure Export",
"Pre Engineered Building Export",
"PEB Export",
"Steel Structure Export",
"Prefab Building Export",
"Modular Building Export",
"Prefabricated Structure Export",
"Steel Building Export",
"Industrial Shed Export",
"Warehouse Structure Export",
"Turnkey Steel Building Export",
"Pre Engineered Steel Building Supply",
"International EPC Project",
"Overseas EPC Contract",
"Global Construction Project",
"International Industrial Project",
"Turnkey Warehouse Project",
"Industrial Construction Export",
"Export of Steel Fabrication",
"Structural Steel Export",
"Fabricated Steel Structure Export",
"Industrial Warehouse Construction",
"Logistics Park Development",
"Distribution Center Construction",
"E-commerce Warehouse Expansion",
"Cold Storage Development",
"Manufacturing Plant Construction",
"Factory Construction Project",
"Greenfield Industrial Project",
"Industrial Park Development",
"Free Zone Development",
"Economic Zone Development",
"Special Economic Zone Project",
"Smart Industrial City",
"Mega Infrastructure Project",
"Airport Cargo Terminal",
"Port Logistics Expansion",
"Renewable Energy Plant Construction",
"Solar Manufacturing Plant",
"EV Manufacturing Plant",
"Battery Gigafactory",
"Data Center Construction",
"Hyperscale Data Center Project",
"USA warehouse construction",
"Canada industrial construction",
"Mexico manufacturing plant expansion",
"Brazil logistics park",
"Middle East industrial project",
"Saudi Arabia NEOM construction",
"UAE warehouse expansion",
"Qatar infrastructure development",
"Oman industrial zone",
"Africa industrial park development",
"Nigeria warehouse construction",
"Kenya logistics hub",
"Egypt industrial zone",
"Europe prefab building demand",
"Germany industrial warehouse",
"UK logistics warehouse demand",
"Netherlands distribution center",
"Poland manufacturing hub",
"Australia industrial construction",
"South East Asia industrial park",
"Vietnam manufacturing expansion",
"Thailand logistics infrastructure",
"Indonesia industrial zone",
"Philippines warehouse development",
"Steel Structure Import",
"Prefab Building Import",
"Construction Steel Import",
"Structural Steel Trade",
"Industrial Equipment Import",
"Construction Material Import",
"Global Steel Demand",
"Steel Export Opportunity",
"International Construction Trade",
"Cross Border EPC Project",
"Global Infrastructure Investment",
"FDI in Manufacturing",
"Foreign Industrial Investment",
"Overseas Construction Contract",
"International Tender EPC",
"World Bank Infrastructure Project",
"ADB Infrastructure Project",
"Export Opportunity Construction",
"Industrial Export Market",
"Engineering Export Services",
"Bechtel",
"Fluor Corporation",
"Kiewit Corporation",
"Turner Construction",
"Skanska",
"Balfour Beatty",
"AECOM",
"Jacobs Engineering",
"Worley",
"SNC-Lavalin",
"Saipem",
"Technip Energies",
"Samsung C&T",
"Hyundai Engineering",
"Daewoo E&C",
"China State Construction Engineering",
"China Railway Construction Corporation",
"Larsen & Toubro International",
"Arabian Construction Company",
"Al Futtaim Engineering",
"Prologis warehouse expansion",
"GLP logistics park",
"Segro warehouse development",
"Panattoni industrial park",
"Goodman Group logistics",
"CBRE industrial leasing",
"JLL industrial report",
"Knight Frank logistics",
"DHL logistics expansion",
"Amazon fulfillment center",
"Walmart distribution center",
"FedEx warehouse hub",
"UPS logistics facility",
"Maersk logistics park"

]

# -----------------------------
# GOVERNMENT / INFRA
# -----------------------------

infra_keywords = [

    "PM Gati Shakti",
    "DMIC",
    "GIDC",
    "industrial corridor",
    "smart city",
    "industrial park",
    "PLI scheme",
    "Make in India",
    "warehouse policy",
"Infrastructure",
"Infra",
"Infrastructure Development",
"Industrial Infrastructure",
"Commercial Infrastructure",
"Civil Infrastructure",
"Core Infrastructure",
"Urban Infrastructure",
"Smart Infrastructure",
"Integrated Infrastructure",
"Infrastructure Project",
"Infra Project",
"Mega Infrastructure Project",
"Industrial Project",
"Greenfield Infrastructure",
"Brownfield Infrastructure",
"Infrastructure Expansion",
"Infrastructure Investment",
"Infrastructure Company",
"Infrastructure Contractor",
"Infrastructure Developer",
"Infrastructure EPC",
"EPC Contractor",
"Turnkey Contractor",
"Engineering Procurement Construction",
"Design Build",
"Turnkey Project",
"Industrial EPC",
"Civil Contractor",
"Industrial Civil Work",
"Structural Engineering",
"Steel Infrastructure",
"Industrial Construction",
"Commercial Construction",
"Factory Construction",
"Warehouse Construction",
"Industrial Building",
"Commercial Building",
"Manufacturing Facility",
"Production Facility",
"Plant Construction",
"Factory Setup",
"Industrial Shed",
"PEB Infrastructure",
"Steel Structure",
"Structural Steel",
"Heavy Steel Structure",
"Steel Fabrication",
"Industrial Fabrication",
"Prefab Infrastructure",
"Modular Infrastructure",
"Pre Engineered Building",
"PEB",
"Warehouse Infrastructure",
"Logistics Infrastructure",
"Supply Chain Infrastructure",
"Cold Chain Infrastructure",
"Industrial Park",
"Logistics Park",
"Business Park",
"Industrial Estate",
"Industrial Cluster",
"SEZ",
"GIDC",
"MIDC",
"Industrial Corridor",
"Freight Corridor",
"Smart City",
"Smart Industrial Park",
"Integrated Township",
"Industrial Township",
"Plug And Play Facility",
"Built To Suit",
"BTS Facility",
"Data Center",
"Hyperscale Data Center",
"Cloud Infrastructure",
"AI Infrastructure",
"Digital Infrastructure",
"Telecom Infrastructure",
"Fiber Infrastructure",
"5G Infrastructure",
"Power Infrastructure",
"Energy Infrastructure",
"Renewable Infrastructure",
"Solar Infrastructure",
"Wind Energy Infrastructure",
"EV Infrastructure",
"Battery Manufacturing",
"Energy Storage Facility",
"Substation Project",
"Transmission Infrastructure",
"Utility Infrastructure",
"Water Infrastructure",
"Pipeline Infrastructure",
"Oil And Gas Infrastructure",
"Petrochemical Infrastructure",
"Refinery Project",
"Mining Infrastructure",
"Port Infrastructure",
"Airport Infrastructure",
"Railway Infrastructure",
"Metro Rail Project",
"Highway Project",
"Expressway Project",
"Road Infrastructure",
"Bridge Construction",
"Tunnel Project",
"Marine Infrastructure",
"Logistics Hub",
"Distribution Center",
"Fulfillment Center",
"Ecommerce Infrastructure",
"Cold Storage",
"Automated Warehouse",
"Industrial Automation",
"Manufacturing Expansion",
"Factory Expansion",
"Capacity Expansion",
"Capex",
"Industrial Investment",
"Project Awarded",
"Upcoming Project",
"Mega Project",
"Construction Begins",
"Groundbreaking",
"Commissioning",
"MoU Signed",
"Industrial Development",
"Economic Zone",
"Special Economic Zone",
"Industrial Real Estate",
"Commercial Real Estate",
"Warehousing Development",
"Integrated Logistics",
"Industrial Solutions",
"Infrastructure Solutions",
"Project Management",
"PMC",
"Engineering Services",
"Industrial Engineering",
"Construction Engineering",
"Smart Factory",
"Advanced Manufacturing",
"Integrated Manufacturing Facility",
"Government Project",
"Government Infrastructure Project",
"Government Investment",
"State Government Project",
"Central Government Project",
"Public Infrastructure Project",
"Industrial Development Project",
"Industrial Infrastructure Development",
"Industrial Area Development",
"Industrial Park Development",
"Mega Industrial Park",
"Integrated Industrial Township",
"Industrial Corridor",
"Economic Corridor",
"Freight Corridor",
"Industrial Cluster Development",
"Manufacturing Cluster",
"Industrial Estate Development",
"SEZ Development",
"Smart Industrial Park",
"Plug And Play Industrial Park",
"Industrial Zone",
"Economic Zone",
"Industrial Region Development",
"GIDC Project",
"MIDC Project",
"RIICO Project",
"APIIC Project",
"TIDCO Project",
"Industrial Expansion Scheme",
"State Industrial Development Corporation",
"Industrial Promotion Policy",
"Industrial Investment Region",
"PM Gati Shakti",
"Make In India",
"National Infrastructure Pipeline",
"NIP Project",
"Industrial Smart City",
"Greenfield Industrial Project",
"Brownfield Industrial Expansion",
"Infrastructure Expansion",
"Capex Project",
"Public Capex",
"Government Tender",
"EPC Tender",
"Turnkey Infrastructure Project",
"Engineering Procurement Construction",
"Industrial EPC Project",
"Bridge Construction",
"Bridge Girder",
"Steel Girder",
"Bridge Infrastructure",
"Flyover Project",
"Elevated Corridor",
"Highway Expansion",
"Expressway Project",
"Road Infrastructure",
"Metro Rail Project",
"Railway Infrastructure",
"Railway Bridge",
"DFCC Project",
"Dedicated Freight Corridor",
"Bullet Train Project",
"Station Redevelopment",
"Airport Expansion",
"Port Development",
"Marine Infrastructure",
"Logistics Park Development",
"Warehouse Park",
"Multi Modal Logistics Park",
"MMLP",
"Cargo Terminal",
"Container Terminal",
"Industrial Warehouse Development",
"Cold Chain Project",
"Cold Storage Infrastructure",
"Power Plant Expansion",
"Transmission Line Project",
"Substation Project",
"Renewable Energy Park",
"Solar Park",
"Wind Energy Park",
"Green Hydrogen Project",
"Battery Manufacturing Project",
"EV Manufacturing Zone",
"Semiconductor Park",
"Electronics Manufacturing Cluster",
"Data Center Park",
"Textile Park",
"Mega Textile Park",
"Food Processing Park",
"Pharma Park",
"Bulk Drug Park",
"Defence Corridor",
"Aerospace Park",
"Industrial Manufacturing Hub",
"Factory Expansion",
"Manufacturing Expansion",
"Industrial Investment Announcement",
"MoU Signed",
"Project Awarded",
"Construction Begins",
"Groundbreaking Ceremony",
"Foundation Stone",
"Cabinet Approval",
"State Cabinet Approval",
"Cabinet Cleared Project",
"Industrial Policy",
"Infrastructure Policy",
"Public Private Partnership",
"PPP Project",
"Smart City Project",
"Urban Infrastructure Development",
"Township Development",
"Commercial Infrastructure",
"Integrated Infrastructure Development",
"National Highway Project",
"NHAI Project",
"PWD Project",
"CPWD Project",
"Smart Infrastructure",
"Urban Development Project",
"City Infrastructure Upgrade",
"Industrial Utility Infrastructure",
"Water Supply Infrastructure",
"Sewage Infrastructure",
"Pipeline Infrastructure",
"Oil And Gas Infrastructure",
"Petrochemical Project",
"Refinery Expansion",
"Mining Infrastructure",
"Steel Plant Expansion",
"Cement Plant Expansion",
"Industrial Construction",
"Heavy Civil Construction",
"Structural Steel Project",
"Steel Structure Project",
"Pre Engineered Building Project",
"PEB Warehouse Project",
"Government Industrial Tender",
"Public Sector Infrastructure",
"PSU Infrastructure Project",
"Industrial Smart Manufacturing Zone"

]